services:
  backend:
    build:
      context: .
    env_file:
      - ../.env
    ports:
      - "${PORT:-9099}:9099"
    volumes:
      - ../certs:/certs:ro
    command: sh -c "npx prisma db push && npm start"
    restart: unless-stopped
