services:
  backend:
    build:
      context: .
    network_mode: "host"
    environment:
      PORT: "${PORT}"
      DATABASE_URL: "${DATABASE_URL}"
      LDAP_URL: "${LDAP_URL}"
      LDAP_DN: "${LDAP_DN}"
      DISABLE_HTTPS: "${DISABLE_HTTPS}"
      DEV_AUTH_BYPASS: "${DEV_AUTH_BYPASS:-false}"
    volumes:
      - /home/user/planqr-secrets/certs:/app/certs:ro
    command: npm run start:container
    restart: always
